extends Node
signal load_requested(group:String)
signal save_requested(group:String)
signal job_pressed(jobHash:String)
signal toppanel_button_pressed(panelName:String)
signal update_chapter_panel()
signal update_learn_panel()
signal part_pressed_learn()
signal part_pressed_test()
signal show_jobs_signal()
signal show_dicts()
signal show_files()
signal import_file(filePath:String)
signal update_test_panel()

signal init_test_panel()
signal switch_hiragana()
